---
version: 1

kind: experiment

framework: pytorch

tags: [Pix2Pix]
 
build:
  image: pytorch/pytorch:1.5-cuda10.1-cudnn7-runtime
  build_steps:
    - pip install -r requirements.txt

environment:
  resources:
    cpu:
      requests: 3
      limits: 3
    memory:
      requests: 10024
      limits: 16098
    gpu:
      requests: 1
      limits: 1

declarations:
  dataroot: /data/Prostate_Reg_KM/anonymized/train
  name: tum_pix2pix_3d
  model: pix2pix_3d
  direction: AtoB
  dataset_mode: volume
  load_mask: True
  input_nc: 1
  output_nc: 1

  batch_size: 4
  lambda_L1: 10
  lambda_Dice: 10
  n_epochs: 100
  n_epochs_decay: 100


run:
  cmd: python -u run.py  --dataroot={{ dataroot }} \
                         --name={{ name }} \
                         --model={{ model }} \
                         --direction={{ direction }} \
                         --input_nc={{ input_nc }} \
                         --output_nc={{ output_nc }} \
                         --dataset_mode={{ dataset_mode }} \
                         --lambda_L1={{ lambda_L1 }} \
                         --lambda_Dice={{ lambda_Dice }} \
                         --n_epochs={{ n_epochs }} \
                         --n_epochs_decay={{ n_epochs_decay }} \
                         --load_mask={{ load_mask }} \
                         --batch_size={{ batch_size }} \